#ifdef __cplusplus
extern "C" {
#endif

#define GAME_STATE_INGAME 5
#define GAME_STATE_FRONTEND 2

#define FRONTEND_MENU_MAIN 2
#define FRONTEND_MENU_RACE 4
#define FRONTEND_MENU_NETWORK 5
#define FRONTEND_MENU_SELECT_TRACK 11
#define FRONTEND_MENU_SELECT_CAR_START 12  // car entrance: writes g_frontendMenuType = SELECT_CAR_END then returns
#define FRONTEND_MENU_SELECT_CAR_END 13    // car display/render case
#define FRONTEND_MENU_TRANSMISSION 14
#define FRONTEND_MENU_OPTIONS 6
#define FRONTEND_MENU_DISPLAY 7
#define FRONTEND_MENU_AUDIO 15
#define FRONTEND_MENU_LOAD_SAVE 16
#define FRONTEND_MENU_SAVE 17
#define FRONTEND_MENU_LOAD 18
#define FRONTEND_MENU_HOST_JOIN_SESSION 19
#define FRONTEND_MENU_SERIAL_HOST 20
#define FRONTEND_MENU_NEXT_CUP 24
#define FRONTEND_MENU_CONTROLLER_CONFIG 32
#define FRONTEND_MENU_GAME_OPTIONS 33
#define FRONTEND_MENU_FAILED_TO_WIN_TD4_CUP 25
#define FRONTEND_MENU_FAILED_TO_WIN_TD4_CUP2 26
#define FRONTEND_MENU_FAILED_TO_WIN_TD4_CUP3 27
#define FRONTEND_MENU_FAILED_TO_WIN_TD4_CUP4 28

#define RACE_TYPE_SINGLE 0
#define RACE_TYPE_CHALLENGE_CUP 1
#define RACE_TYPE_CHAMPIONSHIP_CUP 2
#define RACE_TYPE_PITBULL_CUP 3
#define RACE_TYPE_MASTERS_CUP 4
#define RACE_TYPE_DRAG_RACE 5

void fixStartupCrash(void);
void fixOptions(void);
void skipLogo(void);

#ifdef __cplusplus
}
#endif
